x-app: &app
  image: agroportal/ontologies_api:master
  env_file:
    - .env
  depends_on:
      - solr
      - redis-cache
      - redis-persistent
      - mgrep
      - virtuoso
      - mgrep-watcher
  volumes:
    - ./data/repository:/srv/ontoportal/data/repository
    - ./data/reports:/srv/ontoportal/data/reports
    - ./data/mgrep:/srv/ontoportal/data/mgrep
    - ./data/logs/cron:/srv/ontoportal/ncbo_cron/logs
    - ./data/provision:/srv/ontoportal/ncbo_cron/provision
    - ./data/logs/api:/srv/ontoportal/ontologies_api/logs
  stdin_open: true
  tty: true
  command: /bin/bash

services:
  api:
    <<: *app
    ports:
      - "9393:9393"
    command: bundle exec unicorn -E production -l 9393
    depends_on:
      - solr
      - redis-cache
      - redis-persistent
      - mgrep
      - virtuoso
      - ncbo_cron

  ncbo_cron:
    <<: *app
    image: agroportal/ncbo_cron:master
    command: "bundle exec bin/ncbo_cron"

  mgrep:
    image: ontoportal/mgrep:0.0.3
    entrypoint: [ "/bin/sh", "-c", "
      [ ! -f /srv/mgrep/dictionary/dictionary.txt ] && echo '-376244815943450933\tLES_DOULEURS' > /srv/mgrep/dictionary/dictionary.txt;
      exec /start-mgrep.sh
    " ]
    volumes:
      - ./data/mgrep:/srv/mgrep/dictionary

  mgrep-watcher:
    image: alpine
    volumes:
      - ./data/mgrep:/srv/mgrep/dictionary
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      sh -c "
        apk add --no-cache inotify-tools docker-cli;
        while true; do
          echo 'Watching for changes in /srv/mgrep/dictionary/dictionary.txt';
          inotifywait -e modify,create,delete,move /srv/mgrep/dictionary/dictionary.txt;
          echo 'Change detected, restarting mgrep container';
          docker restart $$(docker ps -q -f name=ontoportal-api_mgrep.1);
        done
      "
    depends_on:
      - mgrep

  redis-cache:
    image: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 10

  redis-persistent:
    # fix this in the configuration of ncbo_cron
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-persistent:/data
      - ./config/redis-persistent.conf:/usr/local/etc/redis/redis.conf

    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 10

  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2.13
    environment:
      - DBA_PASSWORD=dba
      - DAV_PASSWORD=dba
      - VIRT_Parameters_NumberOfBuffers=600000   # ~4.6 GB (600000 * 8KB)
      - VIRT_Parameters_MaxDirtyBuffers=450000
      - VIRT_Parameters_NumOfThreads=40
      - VIRT_Parameters_MaxMem=5000000000        # 5 GB
      - VIRT_Parameters_LogEnable=2
      - VIRT_Parameters_TraceOn=errors
      - VIRT_Database_ErrorLogLevel=7
      - VIRT_Database_Syslog=1
      - VIRT_SPARQL_ResultSetMaxRows=100000
      - VIRT_SPARQL_MaxQueryExecutionTime=600
      - VIRT_SPARQL_MaxQueryCostEstimationTime=600
    ports:
      - "1111:1111"  # Standard Virtuoso port
      - "8890:8890"  # HTTP port for SPARQL endpoint
    volumes:
      - ./config/initdb.d:/opt/virtuoso-opensource/initdb.d
      - ./data/virtuoso/database:/opt/virtuoso-opensource/database
#    healthcheck:
#      test: [ "CMD-SHELL", "curl -sf http://localhost:8890/sparql || exit 1" ]
#      start_period: 10s
#      interval: 60s
#      timeout: 5s
#      retries: 3

  solr:
    image: solr:9.1
    ports:
      - 8983:8983
    command: bin/solr start -cloud -f
    volumes:
      - ./data/solr:/var/solr/data

volumes:
  redis-persistent:

networks:
  default:
    external:
      name: shared-network
